---
title: "Detection and quantification of rat ultrasonic vocalizations"
author: <center><font size="4"><a href="http://marceloarayasalas.weebly.com/">Marcelo Araya-Salas PhD</a></font></center>
output: github_document
date: <center>`r format(Sys.Date(), "%d-%m-%Y")`</center>
editor_options:
  chunk_output_type: console
---

<!-- Description  -->
Detecting ultrasonic vocalization of norway rat under laboratory conditions

*Updated on `r Sys.time()`*

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}

# install.packages("rmarkdown")
library(rmarkdown)

knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%"
)
```

## Table of contents
* [General info](#general-info)
  * [Analyses](#Analyses)
    * [To do list](#to-do-list)
      * [Contact](#contact)

## General info

Code for automatic detection and quantification of acoustics structure in 

## Analysis

- [Recording and annotation formatting](https://rpubs.com/marcelo-araya-salas/811714) 
- [22 kHz detection on recordings without bedding](https://rpubs.com/marcelo-araya-salas/811722) 
- [55 kHz detection on recordings without bedding](https://rpubs.com/marcelo-araya-salas/811726) 
- [22 kHz detection on recordings with bedding](https://rpubs.com/marcelo-araya-salas/818504) 
- [55 kHz detection on recordings with bedding](https://rpubs.com/marcelo-araya-salas/824937) 


## In progress


## To-do list

* Analizar grabaciones con burucha (jaula EE (enriquecimiento) y/o cage-test)
* Enfatizar resultados de campo abierto (grabaciones actualmente analizadas)
* Vignette con ejemplo de como usar la herramienta (paquete) con grabaciones de ratas del CIN
* para detectar 55 khz hacer bandpass 29-100
* para detectar 22 khz hacer bandpass 20-29
* parametros a medir:
    - Numero de vocalizaciones por unidad de tiempo
    - 

* Dar sugerencias para conseguir detecciones mas limpias:
    - menor tasa de muestreo (200 kHz) 
    - usar FLAC
    = grabar con varios canales a diferentes volumenes de grabacion para grabar con buen volumen de grabacion las senales de baja intensidad


## Status
Project is: _done_

## Contact
Created by [Marcelo Araya-Salas](https://marceloarayasalas.weebly.com/)



